# Creating Tensors in TensorfFlow
A few diffeerent ways to create tensors

In [2]:
import tensorflow as tf

I0000 00:00:1790146068.921740   11877 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1790146068.923977   11877 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1790146069.187467   11877 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1790146070.530973   11877 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:0

In [3]:
# create tensor from a list or Numpyarray using tf.convert_to_tensor
import numpy as np

np.set_printoptions(precision=3)

a = np.array([1,2,3], dtype=np.int32)
b = [4,5,6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


E0000 00:00:1790146071.520588   11877 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [4]:
# Similar to NumPy arrays, we can further see the properties
t_ones = tf.ones((2,3))
t_ones.shape

TensorShape([2, 3])

In [5]:
# To get access to tha values that a tensor refers to we can, call the numpy() method on a tensor
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [6]:
# Creating a tensor of constant values can be done as follows
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


# Manipulating the data type and shape of a tensor
Manipulate tensors data types and shapes via several TensorFlow funcitons that cast, reshape, transpose, and sequence

In [7]:
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)

<dtype: 'int64'>


In [8]:
#Transposing a tensor
t = tf.random.uniform(shape=(3, 5))
t_tr = tf.transpose(t)
print(t.shape, '--->', t_tr.shape)

(3, 5) ---> (5, 3)


In [9]:
#Reshaping a tensor (f.eks. from 1D vector to a 2D array)
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5,6))
print(t_reshape.shape)

(5, 6)


In [10]:
#Removing the unnecessary dimensions (dimensions that have size 1, which are not needed)
t = tf.zeros((1, 2, 1, 4, 1))
t_sqz = tf.squeeze(t, axis=(2,4))
print(t.shape, '--->', t_sqz.shape)

(1, 2, 1, 4, 1) ---> (1, 2, 4)


# Applying mathematical operations to tensors
Widley used linear algebra operations, element-wise product, matrix multiplication, and computing norm of a tensor

In [11]:
#Initiate two random tensors, one with uniform distirbution in the range [-1, 1) and the other with standard normal distribution
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5,2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5,2), mean=0.0, stddev=1.0)
print('t1:', t1)
print('t2:', t2)

t1: tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32)
t2: tf.Tensor(
[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]], shape=(5, 2), dtype=float32)


In [12]:
#Compute element-wise product of t1 and t2
t3 = tf.multiply(t1,t2).numpy()
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [13]:
#To compute the mean,sum and the standard deviation along a ceratin axis (or axes), we can use
# tf.math.reduce_mean(), tf.math.reduce_sum(), and tf.math.reduce.std()

#Mean of each column in t1 can be computed:
t4 = tf.math.reduce_mean(t1, axis=0)
print(t4)

tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


In [14]:
# Matrix product between t1 and t2 (t1 x t2.T) can be calculated using tf.linalg.matmul()
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print(t5.numpy())

[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]]


In [15]:
# Or on another hand, computing t1 x t2.T is prefromed by transposing t1, resulting in an array 2x2
t6 = tf.linalg.matmul(t1, t2, transpose_a=True)
print(t6.numpy())

[[-1.711  0.302]
 [ 0.371 -1.049]]


In [16]:
# The norm function is usefull for computing the L^P norm of a tensor
# F.eks. we can calulcate the L^2 norm of t1 as follows
norm_t1 = tf.norm(t1, ord=2, axis=1).numpy()
print(norm_t1)

# verify with numpy that it is correct
print(np.sqrt(np.sum(np.square(t1), axis=1)))

[1.046 0.293 0.504 0.96  0.383]
[1.046 0.293 0.504 0.96  0.383]


# Split, stack, and concatenate tensors
Splitting tensors into multipel tensors, or the reverse: stacking and concatenating tensors into a singel one

In [ ]:
# tf split divides a input tensor into a list of equally sized tensors
# the number of splits choosen must be divisible
#providing number of splits
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())

t_splits = tf.split(t,num_or_size_splits=3)
[item.numpy for item in t_splits]

# A tensor of size 6 was divided into a list of three tensors each with size 2

[0.165 0.901 0.631 0.435 0.292 0.643]


[<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.165, 0.901], dtype=float32)>>,
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.631, 0.435], dtype=float32)>>,
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.292, 0.643], dtype=float32)>>]